<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class ConstitutionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \App\Policy::create(['name'=>'U.S. Constitution', 'short_synopsis'=>'Replacement for the Articles of Confederation','full_synopsis'=>'This is the full synopsis of the proposed policy, with many more details', 'published'=>1, 'public'=>1,'rating'=>rand(-4,4)]);

        \App\Section::create(['content'=>"We the People of the United States, in Order to form a more perfect Union, establish Justice, insure domestic Tranquility, provide for the common defence, promote the general Welfare, and secure the Blessings of Liberty to ourselves and our Posterity, do ordain and establish this Constitution for the United States of America.", 'policy_id'=>20000, 'user_id'=>100000, 'display_order'=>1]); //400000

        \App\Section::create(['title'=>"Article I - Legislative", 'policy_id'=>20000, 'user_id'=>100000, 'display_order'=>2]); //400001
        \App\Section::create(['title'=>"Article II - Executive", 'policy_id'=>20000, 'user_id'=>100000, 'display_order'=>3]); //400002
        \App\Section::create(['title'=>"Article III - Judicial", 'policy_id'=>20000, 'user_id'=>100000, 'display_order'=>4]); //400003
        \App\Section::create(['title'=>"Article IV - States' Relations", 'policy_id'=>20000, 'user_id'=>100000, 'display_order'=>5]); //400004
        \App\Section::create(['title'=>"Article V - Mode of Amendment", 'policy_id'=>20000, 'user_id'=>100000, 'display_order'=>6]); //400005
        \App\Section::create(['title'=>"Article VI - Prior Debts, National Supremacy, Oaths of Office", 'policy_id'=>20000, 'user_id'=>100000, 'display_order'=>7]); //400006
        \App\Section::create(['title'=>"Article VII - Ratification", 'policy_id'=>20000, 'user_id'=>100000, 'display_order'=>8]); //400007

        // Article I
        \App\Section::create(['title'=>"Section 1", 'content'=>"All legislative Powers herein granted shall be vested in a Congress of the United States, which shall consist of a Senate and House of Representatives.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400001, 'display_order'=>1]); //400008
        \App\Section::create(['title'=>"Section 2", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400001, 'display_order'=>2]); //400009
        \App\Section::create(['title'=>"Section 3", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400001, 'display_order'=>3]); //400010
        \App\Section::create(['title'=>"Section 4", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400001, 'display_order'=>4]); //400011
        \App\Section::create(['title'=>"Section 5", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400001, 'display_order'=>5]); //400012
        \App\Section::create(['title'=>"Section 6", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400001, 'display_order'=>6]); //400013
        \App\Section::create(['title'=>"Section 7", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400001, 'display_order'=>7]); //400014
        \App\Section::create(['title'=>"Section 8", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400001, 'display_order'=>8]); //400015
        \App\Section::create(['title'=>"Section 9", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400001, 'display_order'=>9]); //400016
        \App\Section::create(['title'=>"Section 10", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400001, 'display_order'=>10]); //400017

        // Article II
        \App\Section::create(['title'=>"Section 1", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400002, 'display_order'=>1]); //400018
        \App\Section::create(['title'=>"Section 2", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400002, 'display_order'=>2]); //400019
        \App\Section::create(['title'=>"Section 3", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400002, 'display_order'=>3]); //400020
        \App\Section::create(['title'=>"Section 4", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400002, 'display_order'=>4]); //400021

        // Article III
        \App\Section::create(['title'=>"Section 1", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400003, 'display_order'=>1]); //400022
        \App\Section::create(['title'=>"Section 2", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400003, 'display_order'=>2]); //400023
        \App\Section::create(['title'=>"Section 3", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400003, 'display_order'=>3]); //400024

        // Article IV
        \App\Section::create(['title'=>"Section 1", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400004, 'display_order'=>1]); //400025
        \App\Section::create(['title'=>"Section 2", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400004, 'display_order'=>2]); //400026
        \App\Section::create(['title'=>"Section 3", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400004, 'display_order'=>3]); //400027
        \App\Section::create(['title'=>"Section 4", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400004, 'display_order'=>4]); //400028

        // Article V
        \App\Section::create(['title'=>"", 'content'=>"The Congress, whenever two thirds of both Houses shall deem it necessary, shall propose Amendments to this Constitution, or, on the Application of the Legislatures of two thirds of the several States, shall call a Convention for proposing Amendments, which, in either Case, shall be valid to all Intents and Purposes, as Part of this Constitution, when ratified by the Legislatures of three fourths of the several States, or by Conventions in three fourths thereof, as the one or the other Mode of Ratification may be proposed by the Congress; Provided that no Amendment which may be made prior to the Year One thousand eight hundred and eight shall in any Manner affect the first and fourth Clauses in the Ninth Section of the first Article; and that no State, without its Consent, shall be deprived of its equal Suffrage in the Senate.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400005, 'display_order'=>1]); //400008

        // Article VI
        \App\Section::create(['title'=>"", 'content'=>"1: All Debts contracted and Engagements entered into, before the Adoption of this Constitution, shall be as valid against the United States under this Constitution, as under the Confederation.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400006, 'display_order'=>1]); //400008
        \App\Section::create(['title'=>"", 'content'=>"2: This Constitution, and the Laws of the United States which shall be made in Pursuance thereof; and all Treaties made, or which shall be made, under the Authority of the United States, shall be the supreme Law of the Land; and the Judges in every State shall be bound thereby, any Thing in the Constitution or Laws of any State to the Contrary notwithstanding.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400006, 'display_order'=>2]); //400009
        \App\Section::create(['title'=>"", 'content'=>"3: The Senators and Representatives before mentioned, and the Members of the several State Legislatures, and all executive and judicial Officers, both of the United States and of the several States, shall be bound by Oath or Affirmation, to support this Constitution; but no religious Test shall ever be required as a Qualification to any Office or public Trust under the United States.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400006, 'display_order'=>3]); //400010

        // Article VII
        \App\Section::create(['title'=>"", 'content'=>"The Ratification of the Conventions of nine States, shall be sufficient for the Establishment of this Constitution between the States so ratifying the Same.\nThe Word \"the\", being interlined between the seventh and eight Lines of the first Page, The Word \"Thirty\" being partly written on an Erazure in the fifteenth Line of the first Page. The Words \"is tried\" being interlined between the thirty second and thirty third Lines of the first Page and the Word \"the\" being interlined between the forty third and forty fourth Lines of the second Page.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400007, 'display_order'=>1]); //400008


        // A1S2
        \App\Section::create(['title'=>"", 'content'=>"1: The House of Representatives shall be composed of Members chosen every second Year by the People of the several States, and the Electors in each State shall have the Qualifications requisite for Electors of the most numerous Branch of the State Legislature.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400009, 'display_order'=>1]);
        \App\Section::create(['title'=>"", 'content'=>"2: No Person shall be a Representative who shall not have attained to the Age of twenty five Years, and been seven Years a Citizen of the United States, and who shall not, when elected, be an Inhabitant of that State in which he shall be chosen.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400009, 'display_order'=>2]);
        \App\Section::create(['title'=>"", 'content'=>"3: Representatives and direct Taxes shall be apportioned among the several States which may be included within this Union, according to their respective Numbers, which shall be determined by adding to the whole Number of free Persons, including those bound to Service for a Term of Years, and excluding Indians not taxed, three fifths of all other Persons.2  The actual Enumeration shall be made within three Years after the first Meeting of the Congress of the United States, and within every subsequent Term of ten Years, in such Manner as they shall by Law direct. The Number of Representatives shall not exceed one for every thirty Thousand, but each State shall have at Least one Representative; and until such enumeration shall be made, the State of New Hampshire shall be entitled to chuse three, Massachusetts eight, Rhode-Island and Providence Plantations one, Connecticut five, New-York six, New Jersey four, Pennsylvania eight, Delaware one, Maryland six, Virginia ten, North Carolina five, South Carolina five, and Georgia three.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400009, 'display_order'=>3]);
        \App\Section::create(['title'=>"", 'content'=>"4: When vacancies happen in the Representation from any State, the Executive Authority thereof shall issue Writs of Election to fill such Vacancies.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400009, 'display_order'=>4]);
        \App\Section::create(['title'=>"", 'content'=>"5: The House of Representatives shall chuse their Speaker and other Officers; and shall have the sole Power of Impeachment.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400009, 'display_order'=>5]);

        // A1S3
        \App\Section::create(['title'=>"", 'content'=>"1: The Senate of the United States shall be composed of two Senators from each State, chosen by the Legislature thereof,3 for six Years; and each Senator shall have one Vote.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400010, 'display_order'=>1]);
        \App\Section::create(['title'=>"", 'content'=>"2: Immediately after they shall be assembled in Consequence of the first Election, they shall be divided as equally as may be into three Classes. The Seats of the Senators of the first Class shall be vacated at the Expiration of the second Year, of the second Class at the Expiration of the fourth Year, and of the third Class at the Expiration of the sixth Year, so that one third may be chosen every second Year; and if Vacancies happen by Resignation, or otherwise, during the Recess of the Legislature of any State, the Executive thereof may make temporary Appointments until the next Meeting of the Legislature, which shall then fill such Vacancies.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400010, 'display_order'=>2]);
        \App\Section::create(['title'=>"", 'content'=>"3: No Person shall be a Senator who shall not have attained to the Age of thirty Years, and been nine Years a Citizen of the United States, and who shall not, when elected, be an Inhabitant of that State for which he shall be chosen.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400010, 'display_order'=>3]);
        \App\Section::create(['title'=>"", 'content'=>"4: The Vice President of the United States shall be President of the Senate, but shall have no Vote, unless they be equally divided.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400010, 'display_order'=>4]);
        \App\Section::create(['title'=>"", 'content'=>"5: The Senate shall chuse their other Officers, and also a President pro tempore, in the Absence of the Vice President, or when he shall exercise the Office of President of the United States.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400010, 'display_order'=>5]);
        \App\Section::create(['title'=>"", 'content'=>"6: The Senate shall have the sole Power to try all Impeachments. When sitting for that Purpose, they shall be on Oath or Affirmation. When the President of the United States is tried, the Chief Justice shall preside: And no Person shall be convicted without the Concurrence of two thirds of the Members present.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400010, 'display_order'=>6]);
        \App\Section::create(['title'=>"", 'content'=>"7: Judgment in Cases of impeachment shall not extend further than to removal from Office, and disqualification to hold and enjoy any Office of honor, Trust or Profit under the United States: but the Party convicted shall nevertheless be liable and subject to Indictment, Trial, Judgment and Punishment, according to Law.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400010, 'display_order'=>7]);
        
        // A1S4
        \App\Section::create(['title'=>"", 'content'=>"1: The Times, Places and Manner of holding Elections for Senators and Representatives, shall be prescribed in each State by the Legislature thereof; but the Congress may at any time by Law make or alter such Regulations, except as to the Places of chusing Senators.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400011, 'display_order'=>1]);
        \App\Section::create(['title'=>"", 'content'=>"2: The Congress shall assemble at least once in every Year, and such Meeting shall be on the first Monday in December,5 unless they shall by Law appoint a different Day.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400011, 'display_order'=>2]);

        // A1S5
        \App\Section::create(['title'=>"", 'content'=>"1: Each House shall be the Judge of the Elections, Returns and Qualifications of its own Members, and a Majority of each shall constitute a Quorum to do Business; but a smaller Number may adjourn from day to day, and may be authorized to compel the Attendance of absent Members, in such Manner, and under such Penalties as each House may provide.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400012, 'display_order'=>1]);
        \App\Section::create(['title'=>"", 'content'=>"2: Each House may determine the Rules of its Proceedings, punish its Members for disorderly Behaviour, and, with the Concurrence of two thirds, expel a Member.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400012, 'display_order'=>2]);
        \App\Section::create(['title'=>"", 'content'=>"3: Each House shall keep a Journal of its Proceedings, and from time to time publish the same, excepting such Parts as may in their Judgment require Secrecy; and the Yeas and Nays of the Members of either House on any question shall, at the Desire of one fifth of those Present, be entered on the Journal.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400012, 'display_order'=>3]);
        \App\Section::create(['title'=>"", 'content'=>"4: Neither House, during the Session of Congress, shall, without the Consent of the other, adjourn for more than three days, nor to any other Place than that in which the two Houses shall be sitting.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400012, 'display_order'=>4]);

        // A1S6
        \App\Section::create(['title'=>"", 'content'=>"1: The Senators and Representatives shall receive a Compensation for their Services, to be ascertained by Law, and paid out of the Treasury of the United States.6 They shall in all Cases, except Treason, Felony and Breach of the Peace, be privileged from Arrest during their Attendance at the Session of their respective Houses, and in going to and returning from the same; and for any Speech or Debate in either House, they shall not be questioned in any other Place.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400013, 'display_order'=>1]);
        \App\Section::create(['title'=>"", 'content'=>"2: No Senator or Representative shall, during the Time for which he was elected, be appointed to any civil Office under the Authority of the United States, which shall have been created, or the Emoluments whereof shall have been encreased during such time; and no Person holding any Office under the United States, shall be a Member of either House during his Continuance in Office.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400013, 'display_order'=>2]);

        // A1S7
        \App\Section::create(['title'=>"", 'content'=>"1: All Bills for raising Revenue shall originate in the House of Representatives; but the Senate may propose or concur with Amendments as on other Bills.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>1]);
        \App\Section::create(['title'=>"", 'content'=>"2: Every Bill which shall have passed the House of Representatives and the Senate, shall, before it become a Law, be presented to the President of the United States; If he approve he shall sign it, but if not he shall return it, with his Objections to that House in which it shall have originated, who shall enter the Objections at large on their Journal, and proceed to reconsider it. If after such Reconsideration two thirds of that House shall agree to pass the Bill, it shall be sent, together with the Objections, to the other House, by which it shall likewise be reconsidered, and if approved by two thirds of that House, it shall become a Law. But in all such Cases the Votes of both Houses shall be determined by yeas and Nays, and the Names of the Persons voting for and against the Bill shall be entered on the Journal of each House respectively. If any Bill shall not be returned by the President within ten Days (Sundays excepted) after it shall have been presented to him, the Same shall be a Law, in like Manner as if he had signed it, unless the Congress by their Adjournment prevent its Return, in which Case it shall not be a Law.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>2]);
        \App\Section::create(['title'=>"", 'content'=>"3: Every Order, Resolution, or Vote to which the Concurrence of the Senate and House of Representatives may be necessary (except on a question of Adjournment) shall be presented to the President of the United States; and before the Same shall take Effect, shall be approved by him, or being disapproved by him, shall be repassed by two thirds of the Senate and House of Representatives, according to the Rules and Limitations prescribed in the Case of a Bill.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>3]);

        // A1S8
        \App\Section::create(['title'=>"", 'content'=>"1: The Congress shall have Power To lay and collect Taxes, Duties, Imposts and Excises, to pay the Debts and provide for the common Defence and general Welfare of the United States; but all Duties, Imposts and Excises shall be uniform throughout the United States;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>1]);
        \App\Section::create(['title'=>"", 'content'=>"2: To borrow Money on the credit of the United States;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>2]);
        \App\Section::create(['title'=>"", 'content'=>"3: To regulate Commerce with foreign Nations, and among the several States, and with the Indian Tribes;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>3]);
        \App\Section::create(['title'=>"", 'content'=>"4: To establish an uniform Rule of Naturalization, and uniform Laws on the subject of Bankruptcies throughout the United States;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>4]);
        \App\Section::create(['title'=>"", 'content'=>"5: To coin Money, regulate the Value thereof, and of foreign Coin, and fix the Standard of Weights and Measures;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>5]);
        \App\Section::create(['title'=>"", 'content'=>"6: To provide for the Punishment of counterfeiting the Securities and current Coin of the United States;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>6]);
        \App\Section::create(['title'=>"", 'content'=>"7: To establish Post Offices and post Roads;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>7]);
        \App\Section::create(['title'=>"", 'content'=>"8: To promote the Progress of Science and useful Arts, by securing for limited Times to Authors and Inventors the exclusive Right to their respective Writings and Discoveries;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>8]);
        \App\Section::create(['title'=>"", 'content'=>"9: To constitute Tribunals inferior to the supreme Court;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>9]);
        \App\Section::create(['title'=>"", 'content'=>"10: To define and punish Piracies and Felonies committed on the high Seas, and Offences against the Law of Nations;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>10]);
        \App\Section::create(['title'=>"", 'content'=>"11: To declare War, grant Letters of Marque and Reprisal, and make Rules concerning Captures on Land and Water;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>11]);
        \App\Section::create(['title'=>"", 'content'=>"12: To raise and support Armies, but no Appropriation of Money to that Use shall be for a longer Term than two Years;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>12]);
        \App\Section::create(['title'=>"", 'content'=>"13: To provide and maintain a Navy;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>13]);
        \App\Section::create(['title'=>"", 'content'=>"14: To make Rules for the Government and Regulation of the land and naval Forces;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>14]);
        \App\Section::create(['title'=>"", 'content'=>"15: To provide for calling forth the Militia to execute the Laws of the Union, suppress Insurrections and repel Invasions;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>15]);
        \App\Section::create(['title'=>"", 'content'=>"16: To provide for organizing, arming, and disciplining, the Militia, and for governing such Part of them as may be employed in the Service of the United States, reserving to the States respectively, the Appointment of the Officers, and the Authority of training the Militia according to the discipline prescribed by Congress;", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>16]);
        \App\Section::create(['title'=>"", 'content'=>"17: To exercise exclusive Legislation in all Cases whatsoever, over such District (not exceeding ten Miles square) as may, by Cession of particular States, and the Acceptance of Congress, become the Seat of the Government of the United States, and to exercise like Authority over all Places purchased by the Consent of the Legislature of the State in which the Same shall be, for the Erection of Forts, Magazines, Arsenals, dock-Yards, and other needful Buildings;—And", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>17]);
        \App\Section::create(['title'=>"", 'content'=>"18: To make all Laws which shall be necessary and proper for carrying into Execution the foregoing Powers, and all other Powers vested by this Constitution in the Government of the United States, or in any Department or Officer thereof.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400014, 'display_order'=>18]);

        // A1S9
        \App\Section::create(['title'=>"", 'content'=>"1: The Migration or Importation of such Persons as any of the States now existing shall think proper to admit, shall not be prohibited by the Congress prior to the Year one thousand eight hundred and eight, but a Tax or duty may be imposed on such Importation, not exceeding ten dollars for each Person.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400015, 'display_order'=>1]);
        \App\Section::create(['title'=>"", 'content'=>"2: The Privilege of the Writ of Habeas Corpus shall not be suspended, unless when in Cases of Rebellion or Invasion the public Safety may require it.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400015, 'display_order'=>2]);
        \App\Section::create(['title'=>"", 'content'=>"3: No Bill of Attainder or ex post facto Law shall be passed.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400015, 'display_order'=>3]);
        \App\Section::create(['title'=>"", 'content'=>"4: No Capitation, or other direct, Tax shall be laid, unless in Proportion to the Census or Enumeration herein before directed to be taken.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400015, 'display_order'=>4]);
        \App\Section::create(['title'=>"", 'content'=>"5: No Tax or Duty shall be laid on Articles exported from any State.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400015, 'display_order'=>5]);
        \App\Section::create(['title'=>"", 'content'=>"6: No Preference shall be given by any Regulation of Commerce or Revenue to the Ports of one State over those of another: nor shall Vessels bound to, or from, one State, be obliged to enter, clear, or pay Duties in another.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400015, 'display_order'=>6]);
        \App\Section::create(['title'=>"", 'content'=>"7: No Money shall be drawn from the Treasury, but in Consequence of Appropriations made by Law; and a regular Statement and Account of the Receipts and Expenditures of all public Money shall be published from time to time.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400015, 'display_order'=>7]);
        \App\Section::create(['title'=>"", 'content'=>"8: No Title of Nobility shall be granted by the United States: And no Person holding any Office of Profit or Trust under them, shall, without the Consent of the Congress, accept of any present, Emolument, Office, or Title, of any kind whatever, from any King, Prince, or foreign State.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400015, 'display_order'=>8]);

        // A1S10
        \App\Section::create(['title'=>"", 'content'=>"1: No State shall enter into any Treaty, Alliance, or Confederation; grant Letters of Marque and Reprisal; coin Money; emit Bills of Credit; make any Thing but gold and silver Coin a Tender in Payment of Debts; pass any Bill of Attainder, ex post facto Law, or Law impairing the Obligation of Contracts, or grant any Title of Nobility.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400016, 'display_order'=>1]);
        \App\Section::create(['title'=>"", 'content'=>"2: No State shall, without the Consent of the Congress, lay any Imposts or Duties on Imports or Exports, except what may be absolutely necessary for executing it's inspection Laws: and the net Produce of all Duties and Imposts, laid by any State on Imports or Exports, shall be for the Use of the Treasury of the United States; and all such Laws shall be subject to the Revision and Controul of the Congress.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400016, 'display_order'=>2]);
        \App\Section::create(['title'=>"", 'content'=>"3: No State shall, without the Consent of Congress, lay any Duty of Tonnage, keep Troops, or Ships of War in time of Peace, enter into any Agreement or Compact with another State, or with a foreign Power, or engage in War, unless actually invaded, or in such imminent Danger as will not admit of delay.", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400016, 'display_order'=>3]);

        //\App\Section::create(['title'=>"", 'content'=>"", 'policy_id'=>20000, 'user_id'=>100000, 'parent_section_id'=>400017, 'display_order'=>1]);

    }
}
